name: flow

dependencies:
    - python==3.9.13
    - pip>=22.0
    - dill
    - gym==0.21.0
    - grpcio
    - joblib==1.1.0
    - lxml==4.9.1
    - lz4
    - matplotlib==3.5.3
    - nose2==0.9.2
    - opencv
    - plotly==5.10.0
    - psutil
    - scipy==1.9.1
    - six==1.16.0
    - tensorflow==2.9.1
    - pandas==1.4.4
    - pip:
        - path.py
        - python-dateutil
        - pyprind
        - cached_property
        - ray[default]
        - ray[rllib]
        - setproctitle
        - boto3
        - redis==3.3.2
        - pyglet
        - imutils
        - https://akreidieh.s3.amazonaws.com/sumo/flow-0.4.0/sumotools-0.4.0-py3-none-any.whl
        - dm_tree
